language: cpp

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - ninja-build

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install ninja   ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install ninja   ; fi

script:
  - mkdir build_dir
  - cmake -G Ninja -Bbuild_dir -Hmeta_build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_GUI=False
  - cmake --build build_dir --config RelWithDebInfo