language: cpp
os: linux
dist: xenial
jobs:
  include:
    - name: "Xenial Linux"
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - ninja-build
      before_script:
        - curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB | sudo apt-key add -
        - echo "deb https://apt.repos.intel.com/mkl all main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get -qq update
        - sudo apt-get -y install intel-mkl-64bit-2020.0-088
      env:
       - GENERATOR=Ninja
       - MKL_INCLUDE_PATH=/opt/intel/mkl/include
       - MKL_LIBRARY_PATH=/opt/intel/mkl/lib/intel64
    - name: "macOS"
      os: osx
      osx_image: xcode10.2
      compiler: clang
      before_install:
        - brew update
        - brew install ninja
        - curl http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16525/m_mkl_2020.1.216.dmg --output m_mkl_2020.1.216.dmg
        - sudo hdiutil attach m_mkl_2020.1.216.dmg
        - sed 's/=decline/=accept/g' $(find /Volumes/m_mkl_2020.1.216 -name "silent.cfg" -print) > ~/silent.cfg
        - sudo $(find /Volumes/m_mkl_2020.1.216 -name "install.sh" -print) --silent ~/silent.cfg --ignore-cpu
        - sudo hdiutil detach /Volumes/m_mkl_2020.1.216
        - find /opt/intel -name "libmkl_intel_lp64.a"
        - find /opt/intel -name "libmkl_core.a"
        - find /opt/intel -name "libmkl_sequential.a"
      env:
        - GENERATOR=Ninja
        - MKL_INCLUDE_PATH=/opt/intel/mkl/include
        - MKL_LIBRARY_PATH=/opt/intel/mkl/lib/intel64
    - name: "Windows"
      os: windows
      before_install:
        - choco install paket microsoft-visual-cpp-build-tools
        - paket init
        - paket add intelmkl.static.win-x64 --version 2020.1.216
      env:
       - GENERATOR="Visual Studio 14 2015 Win64"
       - MKL_INCLUDE_PATH=C:/Users/travis/.nuget/packages/intelmkl.static.win-x64/2020.1.216/lib/native/include
       - MKL_LIBRARY_PATH=C:/Users/travis/.nuget/packages/intelmkl.static.win-x64/2020.1.216/lib/native/win-x64

script:
  - mkdir build_dir
  - cmake -G "$GENERATOR" -Bbuild_dir -Hmeta_build -DCMAKE_BUILD_TYPE=Release -DBUILD_GUI=False
  - cmake --build build_dir --config Release


# linux
#  add intel apt repo for mkl
# install mkl
# config env

#windows
# use choco to install dotnet cli
# use dotnet cli nuget to install mkl
# config env

#mac
# wget mkl using url
#install mkl
# config env
